# -*- coding: utf-8 -*-
"""One pixel attack.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/168ZrCC6rmZ9yjiWBHTxkKGVkF8ss1mf0
"""

#@title Instalacija i uvoz paketa
!pip -q install ipywidgets

from google.colab import output
output.enable_custom_widget_manager()

import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
from torchvision import datasets, transforms
import numpy as np
import random, math, time
import matplotlib.pyplot as plt
from IPython.display import display, clear_output
import ipywidgets as widgets
from tqdm.notebook import tqdm

plt.rcParams['figure.figsize'] = (6, 6)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("Uređaj:", device)

#@title Učitavanje utreniranog modela

import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import datasets, transforms
import numpy as np
import matplotlib.pyplot as plt

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Normalizacija za CIFAR-10
mean = (0.4914, 0.4822, 0.4465)
std  = (0.2470, 0.2435, 0.2616)

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean, std)
])

# za prikaz (denormalizacija natrag u [0,1])
denorm = transforms.Normalize(
    mean = (-np.array(mean)/np.array(std)).tolist(),
    std  = (1/np.array(std)).tolist()
)

# CIFAR-10 test skup
testset = datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=1, shuffle=False)
class_names = testset.classes


hub_repo = "chenyaofo/pytorch-cifar-models"
hub_model = "cifar10_resnet56"

print(f"Preuzimam {hub_model} s torch.hub ({hub_repo}) ...")
model = torch.hub.load(hub_repo, hub_model, pretrained=True)
model = model.to(device).eval()
print("Model spreman:", hub_model)

# Pomoćne: predikcija i vizualizacija
softmax = nn.Softmax(dim=1)

@torch.no_grad()
def predict_probs(t):
    # t: [1,3,H,W] normalizirano
    model.eval()
    out = model(t.to(device))
    return softmax(out).detach().cpu()  # [1,10]

def tensor_to_img01(t):
    # t: [3,H,W] normirano -> np[H,W,3] u [0,1]
    x = denorm(t.cpu()).clamp(0,1)
    x = x.permute(1,2,0).numpy()
    return x

def topk_bar(probs, ax=None, k=10, title="Distribucija po klasama"):
    # probs: [10]
    idx = np.argsort(-probs)[:k]
    vals = probs[idx]
    labels = [class_names[i] for i in idx]
    if ax is None:
        fig, ax = plt.subplots(figsize=(7,4))
    ax.bar(range(len(vals)), vals)
    ax.set_xticks(range(len(vals)))
    ax.set_xticklabels(labels, rotation=45, ha='right')
    ax.set_ylim(0,1)
    ax.set_title(title)
    return ax, idx, vals

def draw_pixels(ax, coords, color='r'):
    # coords: lista (x,y) u pikselima
    for (x,y) in coords:
        ax.scatter([x+0.5], [y+0.5], s=80, marker='s', facecolors='none', edgecolors=color, linewidths=1.5)
    ax.set_xlim(0,32)
    ax.set_ylim(32,0)
    ax.set_xticks([]); ax.set_yticks([])

#@title Random ispravan uzorak (p_max ≤ τ)
import numpy as np, ipywidgets as widgets, matplotlib.pyplot as plt
from IPython.display import display


try:
    used_idxs
except NameError:
    used_idxs = set()

def _get_predict_probs():
    if "predict_probs" in globals():
        return predict_probs  # očekuje [N,3,H,W] -> [N,C]
    # fallback
    import torch
    import torch.nn.functional as F
    def _fallback_predict_probs(t_batch):
        # t_batch: [N,3,H,W] već normirano mean/std
        dev = globals().get("device", "cpu")
        mdl = globals().get("model", None)
        if mdl is None:
            raise RuntimeError("Model nije definiran u globalima (model).")
        with torch.no_grad():
            out = mdl(t_batch.to(dev))
            return F.softmax(out, dim=1).detach().cpu()
    return _fallback_predict_probs

def _tensor_to_img01_local(t):
    # koristi postojeći helper ako postoji
    if "tensor_to_img01" in globals():
        return tensor_to_img01(t)
    # inače brzi fallback (pretpostavlja globalne mean/std)
    import torch
    x = t.clone().cpu()
    mean_t = torch.tensor(mean).view(3,1,1)
    std_t  = torch.tensor(std).view(3,1,1)
    x = (x * std_t) + mean_t
    x = x.clamp(0,1).permute(1,2,0).numpy()
    return x

# --- UI kontrole ---
tau_slider   = widgets.FloatSlider(value=0.98, min=0.50, max=0.999, step=0.001, readout_format=".3f",
                                   description='τ max p:')
tries_slider = widgets.IntSlider(value=250, min=20, max=2000, step=10, description='Pokušaja:')
btn_pick     = widgets.Button(description='Random ispravan (p_max ≤ τ)', button_style='info')
btn_reset    = widgets.Button(description='Reset korištenih', button_style='warning')
status_rnd   = widgets.HTML(value="Spremno.")
out_rnd      = widgets.Output()


if "index_slider" not in globals():
    index_slider = widgets.IntSlider(value=0, min=0, max=len(testset)-1, step=1, description='Index:')
    display(index_slider)  # pokaži ga korisniku

def pick_random_correct_not_confident(tau=0.98, max_tries=250, relax=True, used=None):
    """
    Traži indeks gdje je model točan i pmax ≤ tau, izbjegavajući 'used'.
    Ako ne nađe unutar max_tries, relaksira tau (0.99, 0.999) i ponovno pokuša.
    Vraća: (idx, pmax, pred, used_tau) ili (None, None, None, None).
    """
    if used is None:
        used = set()
    N = len(testset)
    taus = [tau] + ([0.99, 0.999] if relax else [])
    predict_fn = _get_predict_probs()

    for tcur in taus:
        perm = np.random.permutation(N)
        checks = 0
        for i in perm:
            if checks >= max_tries:
                break
            idx = int(i)
            if idx in used:
                continue  # ne troši pokušaj na već korištene
            x, y = testset[idx]  # x: [3,32,32] normirano CHW
            pr = predict_fn(x.unsqueeze(0))[0].numpy()
            pred = int(np.argmax(pr))
            pmax = float(pr[pred])
            if (pred == y) and (pmax <= tcur):
                return idx, pmax, pred, tcur
            checks += 1
    return None, None, None, None

def on_pick_clicked(b):
    status_rnd.value = "Tražim uzorak…"
    out_rnd.clear_output(wait=True)

    tau = float(tau_slider.value)
    tries = int(tries_slider.value)

    idx, pmax, pred, used_tau = pick_random_correct_not_confident(
        tau=tau, max_tries=tries, relax=True, used=used_idxs
    )

    if idx is None:
        msg_tau = f"(relaksirao do τ={used_tau:.3f})" if used_tau is not None else ""
        status_rnd.value = (f"<b>Nisam našao</b> uzorak u {tries} pokušaja {msg_tau}. "
                            f"Povećaj broj pokušaja ili τ.")
        return

    # zapamti da je ovaj indeks iskorišten (da se ne ponavlja na idući klik)
    used_idxs.add(idx)

    # Postavi/azuriraj globalni index_slider
    try:
        index_slider.max = len(testset)-1
        index_slider.value = idx
    except NameError:
        globals()["index_slider"] = widgets.IntSlider(value=idx, min=0, max=len(testset)-1, step=1, description='Index:')
        display(globals()["index_slider"])

    # Vizualni feedback: slika + bar distribucija prije
    x, y = testset[idx]
    img01 = _tensor_to_img01_local(x)
    pr = _get_predict_probs()(x.unsqueeze(0))[0].numpy()
    pred = int(np.argmax(pr))

    with out_rnd:
        fig = plt.figure(figsize=(10,4))
        gs = fig.add_gridspec(1,2)
        ax1 = fig.add_subplot(gs[0,0]); ax1.imshow(img01); ax1.axis('off')
        ax1.set_title(f"Idx {idx} — GT: {class_names[y]}")
        ax2 = fig.add_subplot(gs[0,1])
        idxs = np.argsort(-pr)[:10]; vals = pr[idxs]; labels=[class_names[i] for i in idxs]
        ax2.bar(range(len(vals)), vals)
        ax2.set_xticks(range(len(vals))); ax2.set_xticklabels(labels, rotation=45, ha='right')
        ax2.set_ylim(0,1); ax2.set_title("Vjerojatnosti (prije)")
        plt.tight_layout(); plt.show()

        print(f"Odabrano: idx={idx} | točno klasificiran kao '{class_names[pred]}' "
              f"s p_max={pr[pred]:.4f} ≤ τ={used_tau:.3f}")

    status_rnd.value = (f"<b>Gotovo.</b> Uzorak postavljen. "
                        f"(korištenih indeksa: {len(used_idxs)})")

def on_reset_clicked(b):
    used_idxs.clear()
    status_rnd.value = "Resetirano. Lista korištenih indeksa je prazna."

btn_pick.on_click(on_pick_clicked)
btn_reset.on_click(on_reset_clicked)

display(widgets.HBox([tau_slider, tries_slider]))
display(widgets.HBox([btn_pick, btn_reset]))
display(status_rnd)
display(out_rnd)

#@title Implementacija DE napada (one-pixel, multi-pixel, ciljani) s napretkom

def clamp01(a):
    return np.clip(a, 0.0, 1.0)

def genes_to_coords_colors(genes, k, H=32, W=32):
    # genes: np.ndarray [5*k] u [0,1]
    # coords [(x,y)*k], cols [(r,g,b)*k] u [0,1]
    # Mapa: (x,y) = floor(val * dim), boja = val
    coords, cols = [], []
    for i in range(k):
        gx, gy, rr, gg, bb = genes[5*i:5*(i+1)]
        x = int(np.floor(gx * W)) % W
        y = int(np.floor(gy * H)) % H
        coords.append((x,y))
        cols.append((rr,gg,bb))
    return coords, cols

def apply_genes_to_img01(img01, genes, k):
    # img01: np[H,W,3] u [0,1] (kopira se)
    # genes: [5*k]
    # Vraća novu sliku (pert01) sa zamijenjenim pikselima na apsolutne RGB vrijednosti
    H,W,_ = img01.shape
    pert = img01.copy()
    coords, cols = genes_to_coords_colors(genes, k, H, W)
    for (x,y),(r,g,b) in zip(coords, cols):
        pert[y, x, 0] = r
        pert[y, x, 1] = g
        pert[y, x, 2] = b
    return pert, coords

def to_model_tensor(img01):
    # np[H,W,3] -> torch[1,3,H,W] normirano
    t = torch.from_numpy(img01).permute(2,0,1).float()
    t = transforms.Normalize(mean, std)(t)
    return t.unsqueeze(0)

@torch.no_grad()
def evaluate_population(base01, label, pop, k, targeted=False, target_class=None, batch=64):
    # base01: np[H,W,3] u [0,1]
    # pop: np[pop_size, 5*k]
    # fitness np[pop_size], probs np[pop_size,10], preds np[pop_size], viz_coords list-of-lists
    N = pop.shape[0]
    fitness_list = []
    probs_list = []
    preds_list = []
    coords_list = []
    for s in range(0, N, batch):
        e = min(N, s+batch)
        imgs = []
        chunk_coords = []
        for i in range(s, e):
            imgp, coords = apply_genes_to_img01(base01, pop[i], k)
            chunk_coords.append(coords)
            imgs.append(imgp)
        tt = torch.stack([to_model_tensor(im)[0] for im in imgs]).to(device)
        out = model(tt)
        pr = F.softmax(out, dim=1).detach().cpu().numpy()
        pd = np.argmax(pr, axis=1)
        probs_list.append(pr)
        preds_list.append(pd)
        # fitness
        if targeted:
            assert target_class is not None
            fit = 1.0 - pr[:, target_class]
        else:
            fit = pr[:, label]
        fitness_list.append(fit)
        coords_list.extend(chunk_coords)
    fitness = np.concatenate(fitness_list, axis=0)
    probs = np.concatenate(probs_list, axis=0)
    preds = np.concatenate(preds_list, axis=0)
    return fitness, probs, preds, coords_list

def de_attack(image_tensor, label, k=1, targeted=False, target_class=None,
              pop_size=120, max_iters=120, Fm=0.5, Cr=0.9, seed=None,
              early_stop=True, verbose=True, progress_cb=None):
    """
    image_tensor: torch[3,H,W]
    progress_cb: callback(iter_idx, max_iters, best_fit, eta_seconds) -> None
    """
    if seed is not None:
        random.seed(seed); np.random.seed(seed)

    # Početne info
    with torch.no_grad():
        probs0 = predict_probs(image_tensor.unsqueeze(0))[0].numpy()
    pred0 = int(np.argmax(probs0))
    base01 = tensor_to_img01(image_tensor)  # np[H,W,3] u [0,1]

    if targeted and target_class is None:
        raise ValueError("Za ciljani napad morate zadati target_class.")

    # Inicijalna populacija u [0,1]
    D = 5*k
    pop = np.random.rand(pop_size, D).astype(np.float32)
    fit, pr, pd, coords_list = evaluate_population(base01, label, pop, k, targeted, target_class)

    # helper za progress
    t0 = time.time()
    def _report(it, best_fit_val):
        if progress_cb is None: return
        if it <= 0:
            progress_cb(0, max_iters, best_fit_val if best_fit_val is not None else float('inf'), None)
        else:
            elapsed = time.time() - t0
            eta = (max_iters - it) * (elapsed / it)
            progress_cb(it, max_iters, best_fit_val if best_fit_val is not None else float('inf'), eta)

    # Provjera ranog uspjeha
    def success_mask(preds):
        if targeted:
            return (preds == target_class)
        else:
            return (preds != label)

    smask = success_mask(pd)
    # inicijalni report (0%)
    _report(0, None)

    if early_stop and smask.any():
        i = int(np.where(smask)[0][0])
        imgp, coords = apply_genes_to_img01(base01, pop[i], k)
        # 100% jer smo gotovi
        if progress_cb is not None:
            progress_cb(max_iters, max_iters, float(fit[i]), 0.0)
        return {
            "success": True,
            "best_genes": pop[i].copy(),
            "best_fit": float(fit[i]),
            "iters": 0,
            "result_img01": imgp,
            "coords": coords,
            "probs_before": probs0,
            "probs_after": pr[i],
            "pred_before": pred0,
            "pred_after": int(pd[i])
        }

    # DE petlja
    best_idx = int(np.argmin(fit))
    best = pop[best_idx].copy()
    best_fit = float(fit[best_idx])

    for it in range(1, max_iters+1):
        trial_pop = pop.copy()
        for i in range(pop_size):
            idxs = list(range(pop_size))
            idxs.remove(i)
            a, b, c = np.random.choice(idxs, 3, replace=False)
            mutant = pop[a] + Fm*(pop[b] - pop[c])
            mutant = clamp01(mutant)

            cross_mask = np.random.rand(D) < Cr
            if not cross_mask.any():
                cross_mask[np.random.randint(0,D)] = True
            trial = np.where(cross_mask, mutant, pop[i])
            trial_pop[i] = trial

        # odabir
        tfit, tpr, tpd, tcoords = evaluate_population(base01, label, trial_pop, k, targeted, target_class)
        better = tfit < fit
        pop[better] = trial_pop[better]
        fit[better] = tfit[better]

        # globalni najbolji
        bi = int(np.argmin(fit))
        if fit[bi] < best_fit:
            best_fit = float(fit[bi]); best = pop[bi].copy()

        # progress report (svaku iteraciju)
        _report(it, best_fit)

        # rano zaustavljanje ako je napad uspjesan
        smask = success_mask(tpd)
        if early_stop and smask.any():
            i = int(np.where(smask)[0][0])
            imgp, coords = apply_genes_to_img01(base01, trial_pop[i], k)
            if progress_cb is not None:
                progress_cb(max_iters, max_iters, float(tfit[i]), 0.0)
            return {
                "success": True,
                "best_genes": trial_pop[i].copy(),
                "best_fit": float(tfit[i]),
                "iters": it,
                "result_img01": imgp,
                "coords": coords,
                "probs_before": probs0,
                "probs_after": tpr[i],
                "pred_before": pred0,
                "pred_after": int(tpd[i])
            }

        if verbose and (it % 10 == 0):
            print(f"Iter {it:4d} | best_fit={best_fit:.4f}")

    # ako je neuspjesno vrati najblizi
    imgp, coords = apply_genes_to_img01(base01, best, k)
    with torch.no_grad():
        probs_after = predict_probs(to_model_tensor(imgp))[0].numpy()
    pred_after = int(np.argmax(probs_after))

    if progress_cb is not None:
        progress_cb(max_iters, max_iters, best_fit, 0.0)

    return {
        "success": (pred_after != label) if not targeted else (pred_after == target_class),
        "best_genes": best.copy(),
        "best_fit": best_fit,
        "iters": max_iters,
        "result_img01": imgp,
        "coords": coords,
        "probs_before": probs0,
        "probs_after": probs_after,
        "pred_before": pred0,
        "pred_after": pred_after
    }

#@title Interaktivni UI: (a) One-pixel (b) Multi-pixel (c) Ciljani — s napretkom/ETA
# widgeti
k_slider = widgets.IntSlider(value=1, min=1, max=10, step=1, description='k (broj piksela):')
target_dd = widgets.Dropdown(options=['— (bez cilja)'] + class_names, description='Cilj:')
pop_size_w = widgets.IntSlider(value=120, min=20, max=400, step=10, description=' (pop_size):') # Veličina populacije
iters_w    = widgets.IntSlider(value=120, min=20, max=500, step=10, description=' (max_iters):') # Maksimalan broj iteracija
F_w        = widgets.FloatSlider(value=0.5, min=0.1, max=1.0, step=0.05, description='(F):') # Mutacijski faktor
Cr_w       = widgets.FloatSlider(value=0.9, min=0.1, max=1.0, step=0.05, description='(CR):') # Faktor križanja
seed_w     = widgets.IntText(value=0, description='Seed:', disabled=False)

btn_a = widgets.Button(description='(a) One-pixel DE', button_style='warning')
btn_b = widgets.Button(description='(b) Multi-pixel', button_style='primary')
btn_c = widgets.Button(description='(c) Ciljani', button_style='danger')

# Napredak / status
prog = widgets.IntProgress(value=0, min=0, max=100, description='Napredak:', bar_style='')
status = widgets.HTML(value="Spremno.")
out_attack = widgets.Output()

def fmt_eta(sec):
    if sec is None or not np.isfinite(sec):
        return "procjena ETA…"
    sec = max(0, int(sec))
    m, s = divmod(sec, 60)
    if m >= 60:
        h, m = divmod(m, 60)
        return f"~{h:d}h {m:02d}m {s:02d}s"
    return f"~{m:02d}m {s:02d}s"

def run_attack(mode):
    # reset napretka
    prog.value = 0
    prog.bar_style = ''  # reset boje
    status.value = "Pokrećem napad…"
    out_attack.clear_output(wait=True)

    idx = index_slider.value
    x, y = testset[idx]
    k = 1 if mode == 'a' else k_slider.value
    targeted = (mode == 'c')
    tclass = None
    if targeted:
        if target_dd.value.startswith('—'):
            status.value = "<b>Molim odaberite ciljanu klasu.</b>"
            return
        tclass = class_names.index(target_dd.value)

    # callback za napredak iz DE petlje
    def progress_cb(it, max_iters, best_fit, eta_sec):
        pct = int(100 * it / max_iters) if max_iters > 0 else 0
        prog.value = min(max(pct, 0), 100)
        bf = best_fit if np.isfinite(best_fit) else float('inf')
        status.value = f"<b>Iter:</b> {it}/{max_iters} | <b>best_fit:</b> {bf:.4f} | <b>preostalo:</b> {fmt_eta(eta_sec)}"

    # pokreni napad
    res = de_attack(
        image_tensor=x, label=y, k=k, targeted=targeted, target_class=tclass,
        pop_size=pop_size_w.value, max_iters=iters_w.value,
        Fm=F_w.value, Cr=Cr_w.value, seed=seed_w.value,
        early_stop=True, verbose=False, progress_cb=progress_cb
    )

    # Prikaz rezultata
    with out_attack:
        before = tensor_to_img01(x)
        after = res["result_img01"]
        pb = res["probs_before"]; pa = res["probs_after"]
        pred_b = res["pred_before"]; pred_a = res["pred_after"]
        coords = res["coords"]

        fig = plt.figure(figsize=(12,8))
        gs = fig.add_gridspec(2,2)

        ax1 = fig.add_subplot(gs[0,0])
        ax1.imshow(before); ax1.set_title(f"Prije: {class_names[pred_b]} ({pb[pred_b]:.2f})"); ax1.axis('off')
        draw_pixels(ax1, coords, color='r')

        ax2 = fig.add_subplot(gs[0,1])
        ax2.imshow(after); ax2.set_title(f"Nakon: {class_names[pred_a]} ({pa[pred_a]:.2f})"); ax2.axis('off')
        draw_pixels(ax2, coords, color='r')

        ax3 = fig.add_subplot(gs[1,0])
        topk_bar(pb, ax=ax3, title="Vjerojatnosti (prije)")

        ax4 = fig.add_subplot(gs[1,1])
        topk_bar(pa, ax=ax4, title="Vjerojatnosti (nakon)")

        fig.suptitle(f"Uspjeh: {res['success']} | iters={res['iters']} | k={k} | coords={coords}")
        plt.tight_layout()
        plt.show()

        if targeted:
            print(f"Cilj: {target_dd.value} | Postignuto: {class_names[pred_a]}")

    # kraj — postavi 100% i poruku
    prog.value = 100
    prog.bar_style = 'success' if res['success'] else 'warning'
    status.value = f"Gotovo. Uspjeh: <b>{res['success']}</b>."

def on_a(b): run_attack('a')
def on_b(b): run_attack('b')
def on_c(b): run_attack('c')

btn_a.on_click(on_a); btn_b.on_click(on_b); btn_c.on_click(on_c)

# Layout
display(widgets.HBox([k_slider, target_dd]))
display(widgets.HBox([pop_size_w, iters_w]))
display(widgets.HBox([F_w, Cr_w, seed_w]))
display(widgets.VBox([prog, status]))
display(widgets.HBox([btn_a, btn_b, btn_c]))
display(out_attack)

#@title Obrana 1: Predobrada — Detect & Fix Outlier Pixel (napad ➜ obrana + usporedba)
import numpy as np, ipywidgets as widgets, matplotlib.pyplot as plt, pandas as pd
from pathlib import Path


def _get_to_model_tensor():
    fn = globals().get("to_model_tensor", None)
    if fn is None:
        from torchvision import transforms
        def _to_model_tensor(img01_):
            t = torch.from_numpy(img01_).permute(2,0,1).float()
            t = transforms.Normalize(mean, std)(t)
            return t.unsqueeze(0)
        globals()["to_model_tensor"] = _to_model_tensor
        fn = _to_model_tensor
    return fn

@torch.no_grad()
def _predict_probs_from_np01(img01):
    fn = _get_to_model_tensor()
    tt = fn(img01).to(device)
    out = model(tt)
    return torch.softmax(out, dim=1).detach().cpu().numpy()[0]

def defense_detect_and_fix(img01, topk=1, window=3, neighbor='median'):
    H,W,_ = img01.shape
    w = int(window if window%2==1 else window+1)
    r = w//2
    pad = np.pad(img01, ((r,r),(r,r),(0,0)), mode='reflect')
    scores = np.zeros((H,W), dtype=np.float32)
    for y in range(H):
        for x in range(W):
            patch = pad[y:y+w, x:x+w, :]
            center = img01[y,x,:]
            neigh = patch.reshape(-1,3)
            ref = np.median(neigh, axis=0) if neighbor=='median' else np.mean(neigh, axis=0)
            scores[y,x] = np.linalg.norm(center - ref, ord=2)
    flat_idx = np.argsort(scores.ravel())[::-1][:int(topk)]
    fixed = img01.copy()
    for f in flat_idx:
        y = f // W; x = f % W
        patch = pad[y:y+w, x:x+w, :]
        neigh = patch.reshape(-1,3)
        ref = np.median(neigh, axis=0) if neighbor=='median' else np.mean(neigh, axis=0)
        fixed[y,x,:] = np.clip(ref,0,1)
    return fixed

# UI
dfix_topk   = widgets.IntSlider(value=1, min=1, max=5, step=1, description='Fix top-k')
dfix_window = widgets.IntSlider(value=3, min=3, max=9, step=2, description='Window')
dfix_neigh  = widgets.Dropdown(options=['median','mean'], value='median', description='Neighbor')
btn_run     = widgets.Button(description='NAPAD + Detect&Fix', button_style='success')
out_box     = widgets.Output()

def _run_attack_current():
    idx = index_slider.value
    x, y = testset[idx]
    targeted = (not target_dd.value.startswith('—'))
    mode = 'c' if targeted else ('b' if k_slider.value>1 else 'a')
    tclass = class_names.index(target_dd.value) if targeted else None
    res = de_attack(
        image_tensor=x, label=y, k=(1 if mode=='a' else k_slider.value),
        targeted=targeted, target_class=tclass,
        pop_size=pop_size_w.value, max_iters=iters_w.value,
        Fm=F_w.value, Cr=Cr_w.value, seed=seed_w.value,
        early_stop=True, verbose=False
    )
    original01 = tensor_to_img01(x)
    attacked01 = res["result_img01"]
    return idx, original01, attacked01, y, res, tclass, targeted, mode

def on_click_run(b):
    out_box.clear_output(wait=True)
    with out_box:
        # ⬇️ OVDJE JE BILA GREŠKA — sada raspakiravamo 8 vrijednosti
        idx, original01, attacked01, y, res, tclass, targeted, mode = _run_attack_current()

        # obrana
        fixed01 = defense_detect_and_fix(attacked01, topk=dfix_topk.value, window=dfix_window.value, neighbor=dfix_neigh.value)

        # baseline (poslije napada)
        pb, pa = res["probs_before"], res["probs_after"]
        pred_b, pred_a = res["pred_before"], res["pred_after"]
        # nakon obrane
        pr_fix = _predict_probs_from_np01(fixed01)
        pred_fix = int(np.argmax(pr_fix))

        # vizual
        fig, axs = plt.subplots(1,3, figsize=(14,4))
        axs[0].imshow(original01); axs[0].axis('off'); axs[0].set_title(f"Original\nGT={class_names[y]}\nPred={class_names[pred_b]} ({pb[pred_b]:.2f})")
        axs[1].imshow(attacked01); axs[1].axis('off'); axs[1].set_title(f"After attack\nPred={class_names[pred_a]} ({pa[pred_a]:.2f})")
        draw_pixels(axs[1], res["coords"], color='r')
        axs[2].imshow(fixed01); axs[2].axis('off'); axs[2].set_title(f"Detect&Fix\nPred={class_names[pred_fix]} ({pr_fix[pred_fix]:.2f})")
        plt.tight_layout(); plt.show()

        # tablica
        rows = [
            {"Scenario":"After attack","Pred":class_names[pred_a],"Prob":float(pa[pred_a]),"Correct":(pred_a==y),
             "BlockedTarget": (pred_a!=tclass) if targeted else None},
            {"Scenario":f"Detect&Fix (k={dfix_topk.value}, w={dfix_window.value}, {dfix_neigh.value})",
             "Pred":class_names[pred_fix],"Prob":float(pr_fix[pred_fix]),"Correct":(pred_fix==y),
             "BlockedTarget": (pred_fix!=tclass) if targeted else None},
        ]
        df = pd.DataFrame(rows)
        display(df)



btn_run.on_click(on_click_run)

display(widgets.HBox([dfix_topk, dfix_window, dfix_neigh]))
display(btn_run, out_box)

#@title Obrana 2: Ensemble (višemodelski prosjek) — napad ➜ ensemble + usporedba
import ipywidgets as widgets, matplotlib.pyplot as plt, numpy as np, pandas as pd, torch
from pathlib import Path
from PIL import Image

def _append_df_to_csv(df, path):
    p = Path(path); header = not p.exists()
    df.to_csv(p, mode="a", index=False, header=header)

# konverzije
def _to_np01(img):
    """str/tensor/PIL/ndarray -> np.float32 [0,1], shape (H,W,3)"""
    if isinstance(img, np.ndarray):
        arr = img
        if arr.ndim == 3 and arr.shape[0] in (1,3) and arr.shape[0] != arr.shape[-1]:
            arr = np.transpose(arr, (1,2,0))
        if arr.ndim == 2:  # grayscale
            arr = np.repeat(arr[...,None], 3, axis=2)
        arr = arr.astype(np.float32)
        if arr.max() > 1.0: arr = arr / 255.0
        return np.clip(arr, 0, 1)
    if torch.is_tensor(img):
        t = img.detach().cpu()
        if t.ndim == 4: t = t[0]
        if t.ndim == 3 and t.shape[0] in (1,3) and t.shape[0] != t.shape[-1]:
            t = t.permute(1,2,0)
        arr = t.numpy().astype(np.float32)
        if arr.ndim == 2: arr = np.repeat(arr[...,None], 3, axis=2)
        if arr.max() > 1.0: arr = arr / 255.0
        return np.clip(arr, 0, 1)
    if isinstance(img, Image.Image):
        return (np.asarray(img.convert('RGB')).astype(np.float32)/255.0).clip(0,1)
    if isinstance(img, str):
        im = Image.open(img).convert('RGB')
        return (np.asarray(im).astype(np.float32)/255.0).clip(0,1)
    raise TypeError(f"result_img01 nepodržan tip: {type(img)}")

def _get_to_model_tensor():
    fn = globals().get("to_model_tensor", None)
    if fn is None:
        from torchvision import transforms
        def _to_model_tensor(img01_):
            t = torch.from_numpy(img01_).permute(2,0,1).float()
            t = transforms.Normalize(mean, std)(t)
            return t.unsqueeze(0)
        globals()["to_model_tensor"] = _to_model_tensor
        fn = _to_model_tensor
    return fn

@torch.no_grad()
def _probs_from_np01_on(model_obj, img01):
    fn = _get_to_model_tensor()
    tt = fn(_to_np01(img01)).to(device)
    out = model_obj(tt)
    return torch.softmax(out, dim=1).detach().cpu().numpy()[0]

@torch.no_grad()
def _probs_from_tensor_on(model_obj, x_tensor_normed):
    out = model_obj(x_tensor_normed.unsqueeze(0).to(device))
    return torch.softmax(out, dim=1).detach().cpu().numpy()[0]

# ===== Ensemble modeli (torch.hub) =====
HUB_REPO = "chenyaofo/pytorch-cifar-models"
HUB_MODELS = {
    "ResNet56":   "cifar10_resnet56",
    "VGG13-BN":  "cifar10_vgg13_bn",
    "VGG16-BN":   "cifar10_vgg16_bn",
    "RepVGG-A2": "cifar10_repvgg_a2",
}
_ens_cache = {}
def _load_hub_model(name):
    if name in _ens_cache: return _ens_cache[name]
    hub_id = HUB_MODELS[name]
    print(f"Učitavam {name} ({hub_id})…")
    m = torch.hub.load(HUB_REPO, hub_id, pretrained=True).to(device).eval()
    _ens_cache[name] = m
    return m

@torch.no_grad()
def _ensemble_probs_from_np01(img01, names):
    fn = _get_to_model_tensor()
    tt = fn(_to_np01(img01)).to(device)
    probs = []
    for nm in names:
        m = _load_hub_model(nm)
        pr = torch.softmax(m(tt), dim=1)
        probs.append(pr)
    avg = torch.stack(probs, 0).mean(0)[0]
    return avg.detach().cpu().numpy()

# ===== Lokalan napad-helper (ne oslanja se na globalni _run_attack_current) =====
def _run_attack_current_ens():
    """
    Vrati: (idx, original01_np, attacked01_np, y, res, tclass, targeted, mode)
    """
    idx = index_slider.value
    x, y = testset[idx]  # x je već normiran (mean/std)
    targeted = (not target_dd.value.startswith('—'))
    mode = 'c' if targeted else ('b' if k_slider.value>1 else 'a')
    tclass = class_names.index(target_dd.value) if targeted else None

    # pokreni DE (bez progress_cb — dovoljno za ensemble UI)
    res = de_attack(
        image_tensor=x, label=y, k=(1 if mode=='a' else k_slider.value),
        targeted=targeted, target_class=tclass,
        pop_size=pop_size_w.value, max_iters=iters_w.value,
        Fm=F_w.value, Cr=Cr_w.value, seed=seed_w.value,
        early_stop=True, verbose=False
    )

    original01 = tensor_to_img01(x)            # np[0,1]
    attacked01 = _to_np01(res["result_img01"])

    # osiguraj pb/pa/pred_*
    pb = res.get("probs_before")
    if pb is None:
        pb = _probs_from_tensor_on(model, x); res["probs_before"] = pb
    pa = res.get("probs_after")
    if pa is None:
        pa = _probs_from_np01_on(model, attacked01); res["probs_after"] = pa
    if "pred_before" not in res: res["pred_before"] = int(np.argmax(pb))
    if "pred_after"  not in res: res["pred_after"]  = int(np.argmax(pa))

    return idx, original01, attacked01, y, res, tclass, targeted, mode

# ===== UI =====
ens_select = widgets.SelectMultiple(options=list(HUB_MODELS.keys()), value=("ResNet56","VGG16-BN"), description="Ensemble:", rows=5)
btn_run    = widgets.Button(description='NAPAD + Ensemble', button_style='success')
out_box    = widgets.Output()

def on_click_run(b):
    out_box.clear_output(wait=True)
    with out_box:
        names = list(ens_select.value)
        if not names:
            print("Odaberi barem jedan model u ensemble-u."); return

        idx, original01, attacked01, y, res, tclass, targeted, mode = _run_attack_current_ens()
        pb, pa = res["probs_before"], res["probs_after"]
        pred_b, pred_a = res["pred_before"], res["pred_after"]

        pr_ens = _ensemble_probs_from_np01(attacked01, names)
        pred_ens = int(np.argmax(pr_ens))

        # slike + bar chartovi
        fig = plt.figure(figsize=(14,4))
        gs = fig.add_gridspec(1,3)

        ax0 = fig.add_subplot(gs[0,0]); ax0.imshow(original01); ax0.axis('off')
        ax0.set_title(f"Original\nGT={class_names[y]}\nPred={class_names[pred_b]} ({pb[pred_b]:.2f})")

        ax1 = fig.add_subplot(gs[0,1]); ax1.imshow(attacked01); ax1.axis('off')
        ax1.set_title(f"After attack\nPred={class_names[pred_a]} ({pa[pred_a]:.2f})")
        draw_pixels(ax1, res["coords"], color='r')

        ax2 = fig.add_subplot(gs[0,2])
        idxs = np.argsort(-pr_ens)[:10]; labels=[class_names[i] for i in idxs]; vals=pr_ens[idxs]
        ax2.bar(range(len(vals)), vals); ax2.set_xticks(range(len(vals))); ax2.set_xticklabels(labels, rotation=45, ha='right')
        ax2.set_ylim(0,1); ax2.set_title(f"Ensemble: {', '.join(names)}\nPred={class_names[pred_ens]} ({pr_ens[pred_ens]:.2f})")
        plt.tight_layout(); plt.show()

        rows = [
            {"Scenario":"After attack","Pred":class_names[pred_a],"Prob":float(pa[pred_a]),"Correct":(pred_a==y),
             "BlockedTarget": (pred_a!=tclass) if targeted else None},
            {"Scenario":f"Ensemble ({', '.join(names)})","Pred":class_names[pred_ens],"Prob":float(pr_ens[pred_ens]),"Correct":(pred_ens==y),
             "BlockedTarget": (pred_ens!=tclass) if targeted else None},
        ]
        df = pd.DataFrame(rows)
        display(df)


btn_run.on_click(on_click_run)
display(ens_select, btn_run, out_box)

#@title Obrana 3 (s napretkom): Fine-tuning na otrovanim slikama za klasu ➜ Ponovi napad + prikaži 5 uzoraka
import copy, random, time, numpy as np, torch, torch.nn as nn, torch.optim as optim
import ipywidgets as widgets
import matplotlib.pyplot as plt
from torchvision import datasets, transforms
from torch.utils.data import Dataset, DataLoader
from PIL import Image

# helper funkcije
def _to_np01(img):
    if isinstance(img, np.ndarray):
        arr = img
        if arr.ndim == 3 and arr.shape[0] in (1,3) and arr.shape[0] != arr.shape[-1]:
            arr = np.transpose(arr, (1,2,0))
        if arr.ndim == 2: arr = np.repeat(arr[...,None], 3, axis=2)
        arr = arr.astype(np.float32)
        if arr.max() > 1.0: arr = arr / 255.0
        return np.clip(arr, 0, 1)
    if torch.is_tensor(img):
        t = img.detach().cpu()
        if t.ndim == 4: t = t[0]
        if t.ndim == 3 and t.shape[0] in (1,3) and t.shape[0] != t.shape[-1]:
            t = t.permute(1,2,0)
        arr = t.numpy().astype(np.float32)
        if arr.ndim == 2: arr = np.repeat(arr[...,None], 3, axis=2)
        if arr.max() > 1.0: arr = arr / 255.0
        return np.clip(arr, 0, 1)
    if isinstance(img, Image.Image):
        return (np.asarray(img.convert('RGB')).astype(np.float32)/255.0).clip(0,1)
    if isinstance(img, str):
        im = Image.open(img).convert('RGB')
        return (np.asarray(im).astype(np.float32)/255.0).clip(0,1)
    raise TypeError(f"Nepodržan tip: {type(img)}")

def _get_to_model_tensor():
    fn = globals().get("to_model_tensor", None)
    if fn is None:
        def _to_model_tensor(img01_):
            t = torch.from_numpy(img01_).permute(2,0,1).float()
            t = transforms.Normalize(mean, std)(t)
            return t.unsqueeze(0)
        globals()["to_model_tensor"] = _to_model_tensor
        fn = _to_model_tensor
    return fn

@torch.no_grad()
def _probs_from_np01_on(model_obj, img01):
    fn = _get_to_model_tensor()
    tt = fn(_to_np01(img01)).to(device)
    out = model_obj(tt)
    return torch.softmax(out, dim=1).detach().cpu().numpy()[0]

@torch.no_grad()
def _probs_from_tensor_on(model_obj, x_tensor_normed):
    out = model_obj(x_tensor_normed.unsqueeze(0).to(device))
    return torch.softmax(out, dim=1).detach().cpu().numpy()[0]

# poisson
def _poison_random_pixels(img01, k=1):
    H,W,_ = img01.shape
    out = img01.copy()
    for _ in range(int(k)):
        x = np.random.randint(0, W)
        y = np.random.randint(0, H)
        out[y,x,:] = np.random.rand(3)  # nasumična boja
    return out

class PoisonedCIFAR10PerClass(Dataset):
    """
    Uzimamo točno 'count' primjeraka iz train skupa za 'target_class',
    na svakom pravimo k nasumičnih pixel-otrova (label ostaje isti),
    vraćamo NORMIRANI tensor za model. Sprema i kopije slika za prikaz.
    """
    def __init__(self, root='./data', target_class=0, count=50, k_pixels=1):
        base = datasets.CIFAR10(root=root, train=True, download=True, transform=transforms.ToTensor())
        idxs = [i for i, (_, y) in enumerate(base) if y == target_class]
        if len(idxs) < count:
            raise ValueError(f"Traženo {count} uzoraka za klasu {target_class}, a dostupno je {len(idxs)}.")
        random.shuffle(idxs)
        self.items = []
        self.sample_imgs_np01 = []  # za kasniji prikaz
        for i in idxs[:count]:
            x_t, y = base[i]     # [3,32,32] u [0,1]
            img01 = x_t.permute(1,2,0).numpy()
            poisoned = _poison_random_pixels(img01, k=k_pixels)
            self.sample_imgs_np01.append(poisoned)
            t = torch.from_numpy(poisoned).permute(2,0,1).float()
            t = transforms.Normalize(mean, std)(t)
            self.items.append((t, y))
    def __len__(self): return len(self.items)
    def __getitem__(self, i): return self.items[i]

# ---------- UI ----------
def _default_ft_class():
    try:
        x, y = testset[index_slider.value]
        return class_names[y]
    except Exception:
        return class_names[0]

ft_class_dd = widgets.Dropdown(options=class_names, value=_default_ft_class(), description='FT klasa:')
ft_kpix     = widgets.IntSlider(value=1, min=1, max=5, step=1, description='Poison k')
ft_count    = widgets.IntSlider(value=50, min=50, max=200, step=10, description='FT broj')  # default 50
ft_epochs   = widgets.IntSlider(value=2, min=1, max=10, step=1, description='Epochs')
ft_lr       = widgets.FloatSlider(value=1e-4, min=1e-5, max=5e-4, step=1e-5, readout_format=".0e", description='LR')
ft_bs       = widgets.IntSlider(value=64, min=16, max=256, step=16, description='Batch')

# feedback UI
btn_run_ft  = widgets.Button(description='Generiraj & Fine-tune & Ponovi napad', button_style='warning')
prog_epoch  = widgets.IntProgress(value=0, min=0, max=int(ft_epochs.value), description='Epoch:')
prog_batch  = widgets.IntProgress(value=0, min=0, max=1, description='Batch:')
status_html = widgets.HTML(value="Spremno.")
out_ft      = widgets.Output()

def _update_prog_configs(num_epochs, num_batches):
    prog_epoch.min = 0; prog_epoch.max = int(num_epochs); prog_epoch.value = 0; prog_epoch.bar_style = ''
    prog_batch.min = 0; prog_batch.max = max(1, int(num_batches)); prog_batch.value = 0; prog_batch.bar_style = ''
    status_html.value = "Pripremam podatke…"

def on_run_ft(b):
    btn_run_ft.disabled = True
    out_ft.clear_output(wait=True)
    status_html.value = "Pripremam dataset…"

    try:
        # 1) Dataset
        target_name = ft_class_dd.value
        target_id = class_names.index(target_name)
        ds = PoisonedCIFAR10PerClass(target_class=target_id, count=int(ft_count.value), k_pixels=int(ft_kpix.value))
        dl = DataLoader(ds, batch_size=int(ft_bs.value), shuffle=True, num_workers=2, pin_memory=True)
        _update_prog_configs(num_epochs=int(ft_epochs.value), num_batches=len(dl))

        # 2) Fine-tune (s progress barovima)
        model_orig = globals()["model"]
        model_finetuned = copy.deepcopy(model_orig).to(device).train()
        opt = optim.Adam(model_finetuned.parameters(), lr=float(ft_lr.value))
        crit = nn.CrossEntropyLoss()

        t_total_start = time.time()
        for ep in range(1, int(ft_epochs.value) + 1):
            epoch_start = time.time()
            losses = []
            prog_epoch.value = ep - 1
            prog_batch.value = 0

            for i, (xb, yb) in enumerate(dl, 1):
                xb = xb.to(device); yb = yb.to(device)
                opt.zero_grad()
                out = model_finetuned(xb)
                loss = crit(out, yb)
                loss.backward()
                opt.step()

                losses.append(float(loss.item()))
                prog_batch.value = i

                # ETA i status
                elapsed = time.time() - epoch_start
                eta_b = (elapsed / i) * (len(dl) - i) if i > 0 else 0.0
                status_html.value = (f"<b>FT ep {ep}/{int(ft_epochs.value)}</b> | "
                                     f"batch {i}/{len(dl)} | "
                                     f"loss(avg) ≈ {np.mean(losses[-50:]):.4f} | "
                                     f"ETA epoch ≈ {int(eta_b)//60:02d}m {int(eta_b)%60:02d}s")

            prog_epoch.value = ep

        status_html.value = "<b>Fine-tuning gotovo.</b>"
        prog_epoch.bar_style = 'success'; prog_batch.bar_style = 'success'
        model_finetuned.eval()

        # 3) Prikaži 5 nasumičnih otrovanih slika iz FT skupa
        with out_ft:
            print(f"Primjeri otrovanih slika za klasu '{target_name}' (5 nasumičnih):")
            samp = random.sample(ds.sample_imgs_np01, k=min(5, len(ds.sample_imgs_np01)))
            fig = plt.figure(figsize=(10,2.2))
            for i, im in enumerate(samp, 1):
                ax = fig.add_subplot(1, len(samp), i)
                ax.imshow(np.clip(im,0,1)); ax.axis('off')
            plt.show()

        # 4) Ponovi napad NA TRENUTNI indeks, ali protiv FT modela (privremeno zamijeni globalni model)
        idx = index_slider.value
        x, y = testset[idx]
        original01 = tensor_to_img01(x)
        targeted_mode = (not target_dd.value.startswith('—'))
        mode = 'c' if targeted_mode else ('b' if k_slider.value>1 else 'a')
        tclass = class_names.index(target_dd.value) if targeted_mode else None

        globals()["model"] = model_finetuned
        try:
            res_ft = de_attack(
                image_tensor=x, label=y, k=(1 if mode=='a' else k_slider.value),
                targeted=targeted_mode, target_class=tclass,
                pop_size=pop_size_w.value, max_iters=iters_w.value,
                Fm=F_w.value, Cr=Cr_w.value, seed=seed_w.value,
                early_stop=True, verbose=False
            )
        finally:
            globals()["model"] = model_orig  # vrati original bez obzira na ishod

        attacked01_ft = _to_np01(res_ft["result_img01"])
        pb_ft = _probs_from_tensor_on(model_finetuned, x)
        pa_ft = _probs_from_np01_on(model_finetuned, attacked01_ft)
        pred_b_ft, pred_a_ft = int(np.argmax(pb_ft)), int(np.argmax(pa_ft))

        with out_ft:
            fig = plt.figure(figsize=(12,4))
            gs = fig.add_gridspec(1,3)
            ax0 = fig.add_subplot(gs[0,0]); ax0.imshow(original01); ax0.axis('off')
            ax0.set_title(f"Original\nGT={class_names[y]}\nFT pred={class_names[pred_b_ft]} ({pb_ft[pred_b_ft]:.2f})")
            ax1 = fig.add_subplot(gs[0,1]); ax1.imshow(attacked01_ft); ax1.axis('off')
            ax1.set_title(f"Attack vs FT model\npred={class_names[pred_a_ft]} ({pa_ft[pred_a_ft]:.2f})")
            try:
                draw_pixels(ax1, res_ft["coords"], color='r')
            except Exception:
                pass
            ax2 = fig.add_subplot(gs[0,2])
            idxs = np.argsort(-pa_ft)[:10]; labels=[class_names[i] for i in idxs]; vals=pa_ft[idxs]
            ax2.bar(range(len(vals)), vals)
            ax2.set_xticks(range(len(vals))); ax2.set_xticklabels(labels, rotation=45, ha='right')
            ax2.set_ylim(0,1); ax2.set_title("FT model — top vjerojatnosti")
            plt.tight_layout(); plt.show()

            print("--- SAŽETAK ---")
            if mode == 'c':
                print(f"Ciljani napad na '{class_names[tclass]}' — uspjeh = {pred_a_ft == tclass}")
            else:
                print(f"Untargeted napad — uspjeh (pogrešna klasa) = {pred_a_ft != y}")
            print(f"Prije napada (FT): {class_names[pred_b_ft]}  p={pb_ft[pred_b_ft]:.3f}")
            print(f"Nakon napada (FT): {class_names[pred_a_ft]}  p={pa_ft[pred_a_ft]:.3f}")

    except Exception as e:
        status_html.value = f"<b>Greška:</b> {e}"
        prog_epoch.bar_style = 'danger'; prog_batch.bar_style = 'danger'
        raise
    finally:
        btn_run_ft.disabled = False

# Layout
controls_top = widgets.HBox([ft_class_dd, ft_kpix, ft_count])
controls_mid = widgets.HBox([ft_epochs, ft_lr, ft_bs])
display(widgets.VBox([controls_top, controls_mid]))
display(widgets.VBox([prog_epoch, prog_batch, status_html]))
display(btn_run_ft)
display(out_ft)

btn_run_ft.on_click(on_run_ft)